# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='temp',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='climate.Country'),
        ),
    ]
