# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_auto_20180119_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp',
            new_name='MaxTemp',
        ),
    ]
