# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0003_auto_20180119_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinTemp',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('climate.maxtemp',),
        ),
    ]
