# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_auto_20180119_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxtemp',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_countries', to='climate.Country'),
        ),
        migrations.AlterField(
            model_name='mintemp',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_countries', to='climate.Country'),
        ),
    ]
